// addEventListener('keydown',function (a) {
//     console.log(a.code);
    
//        if (a.code == 'ArrowUp' ) {
//         console.log('up');
//         player.velocity.y -= 10;
      
//      } 
//      else if(a.code == 'ArrowDown'){
//        player.velocity.y += 10;
      
//     }
    
    
//      if(a.code == 'ArrowRight' && player.position.x <400 ){
//        player.velocity.x += 10;
      
//        console.log('there');
    
//        }else if (a.code == 'ArrowLeft'&& player.position.x > 100) {
//           player.velocity.x -= 10;   
//           } else{
//              player.velocity.x = 0 
             
//              if (a.code == 'ArrowRight') {
//                 platforms.forEach(platform => {
//                    platform.position.x -=10
//                 offset +=5
                
                   
//                 console.log(offset);
                       
//                    });
//              }else if(a.code == 'ArrowLeft')
    
//              platforms.forEach(platform => {
//                    platform.position.x +=10
//                 offset -=5
//                 console.log(offset);
                       
//                    });
                
//           }
      
//     }) 
//     addEventListener('keyup',function (a) {
//          if (a.code == 'ArrowUp') {
//                  player.velocity.y = 0;
//           } else if(a.code == 'ArrowDown'){
//               player.velocity.y = 0;
//           }
//            else if (a.code == 'ArrowLeft') {
//               player.velocity.x = 0;
//         } else if(a.code == 'ArrowRight' ){
//            player.velocity.x = 0;
    
//         }
//       })
    